// Define windows width and height
#define WINDOWS_WIDTH glutGet(GLUT_SCREEN_WIDTH)
#define WINDOWS_HEIGHT glutGet(GLUT_SCREEN_HEIGHT)
#define WINDOWS_CENTER_X WINDOWS_WIDTH / 2
#define WINDOWS_CENTER_Y WINDOWS_HEIGHT / 2

#define WATCH_BODY_RADIUS 550

#define COMPLICATION_RING_RADIUS 320

// Group Strap
#define STRAP_WIDTH 50
#define STRAP_HEIGHT 300
#define STRAP_CORNER_RADIUS 25
#define STRAP_HOLE_WIDTH 70
#define STRAP_HOLE_HEIGHT 30
#define STRAP_HOLE_CORNER_RADIUS 10

// Group Background
#define BACKGROUND_CIRCLE_RADIUS 500
#define OUTER_RING_RADIUS 480
#define OUTER_RING_THICKNESS 20
#define SECONDS_RING_RADIUS 465
#define SECONDS_RING_THICKNESS 10

// Group Center Piece
#define CORE_CIRCLE_RADIUS 160
#define MINUTES_CIRCLE_RADIUS 175

#define ANALOG_INDICATOR_WIDTH 0.7
#define ANALOG_INDICATOR_LENGTH 15
#define ANALOG_QUATER_INDICATOR_LENGTH 40

// Group Date and Day
#define DATE_BOX_WIDTH 180
#define DATE_BOX_HEIGHT 70
#define DATE_BOX_CORNER_RADIUS 15
#define DAY_BOX_WIDTH 80
#define DAY_BOX_HEIGHT 60
#define DAY_BOX_CORNER_RADIUS 15

#define HOUR_CIRCLE_RADIUS 25