// Define windows width and height
#define WINDOWS_WIDTH 1000
#define WINDOWS_HEIGHT 1000
#define WINDOWS_CENTER_X WINDOWS_WIDTH / 2
#define WINDOWS_CENTER_Y WINDOWS_HEIGHT / 2
// #define WINDOWS_WIDTH 2000
// #define WINDOWS_HEIGHT 2000
#define WINDOWS_INIT_X (glutGet(GLUT_SCREEN_WIDTH) - WINDOWS_WIDTH) / 2
#define WINDOWS_INIT_Y (glutGet(GLUT_SCREEN_HEIGHT) - WINDOWS_HEIGHT) / 2

// Define text scale
#define TEXT_SIZE_SMALL 1
#define TEXT_SIZE_MEDIUM 2
#define TEXT_SIZE_LARGE 2.5

#define COMPLICATION_RING_RADIUS 320

// Group Background
#define BAKGROUND_CIRCLE_RADIUS 500
#define OUTER_RING_RADIUS 480
#define OUTER_RING_THICKNESS 20
#define SECONDS_RING_RADIUS 465
#define SECONDS_RING_THICKNESS 10

// Group Center Circles
#define CORE_CIRCLE_RADIUS 160
#define MINUTES_CIRCLE_RADIUS 175

#define ANALOG_INDICATOR_WIDTH 0.7
#define ANALOG_INDICATOR_LENGTH 15
#define ANALOG_QUATER_INDICATOR_LENGTH 40

// Group Date and Day
#define DATE_BOX_WIDTH 180
#define DATE_BOX_HEIGHT 70
#define DATE_BOX_CORNER_RADIUS 15
#define DAY_BOX_WIDTH 80
#define DAY_BOX_HEIGHT 60
#define DAY_BOX_CORNER_RADIUS 15

#define HOUR_CIRCLE_RADIUS 25
